export interface CTDNode {
  id: string;
  code?: string; // Node number or tag, e.g. "1.0", "1.2.1", "3.2.S.1.1"
  docId?: string; // Document ID tag, e.g. "01001", "25001", "12001"
  title: string;
  isFolder?: boolean;
  children?: CTDNode[];
}

export const ECTD_FULL_TREE: CTDNode[] = [
  {
    id: "m1",
    code: "Module 1",
    title: "Administrative Information & Prescribing Information",
    isFolder: true,
    children: [
      { id: "1.0", code: "1.0.", docId: "01001", title: "Cover letter" },
      { id: "1.1", code: "1.1.", docId: "25001", title: "Table of contents" },
      {
        id: "1.2",
        code: "1.2",
        title: "General Documentation",
        isFolder: true,
        children: [
          {
            id: "1.2.1",
            code: "1.2.1",
            title: "Application for registration of a medicinal product",
            isFolder: true,
            children: [
              {
                id: "1.2.1-01002",
                code: "1.2.1.",
                docId: "01002",
                title: "Application for registration of a medicinal product for medical use (bringing registration dossier into compliance with EAEU requirements)",
              },
              {
                id: "1.2.1-01003",
                code: "1.2.1.",
                docId: "01003",
                title: "Application for amendments to the registration dossier of a medicinal product",
              },
              {
                id: "1.2.1-01004",
                code: "1.2.1.",
                docId: "01004",
                title: "Application for re-registration of a medicinal product",
              },
            ],
          },
          {
            id: "1.2.2-01005",
            code: "1.2.2.",
            docId: "01005",
            title: "Document confirming payment of expert work fees and/or registration fees (duties) in accordance with EAEU member state legislation",
          },
          {
            id: "1.2.3",
            code: "1.2.3",
            title: "Copy of certificate for medicinal product in accordance with WHO recommended format",
            isFolder: true,
            children: [
              {
                id: "1.2.3-01006",
                code: "1.2.3.",
                docId: "01006",
                title: "Copy of the certificate for the medicinal product (properly certified) according to WHO-recommended format",
              },
              {
                id: "1.2.3-01007",
                code: "1.2.3.",
                docId: "01007",
                title: "Document confirming registration in manufacturing country and/or marketing authorization holder country",
              },
              {
                id: "1.2.3-01008",
                code: "1.2.3.",
                docId: "01008",
                title: "Explanatory note justifying the absence of registration data for the medicinal product",
              },
            ],
          },
          {
            id: "1.2.4",
            code: "1.2.4",
            title: "Translation into Russian and copy of expert report issued upon registration",
            isFolder: true,
            children: [
              {
                id: "1.2.4-01009",
                code: "1.2.4.",
                docId: "01009",
                title: "Expert report issued upon registration of medicinal product in manufacturing or MAH country",
              },
              {
                id: "1.2.4-01010",
                code: "1.2.4.",
                docId: "01010",
                title: "Russian translation of expert report issued upon registration in manufacturing or MAH country",
              },
            ],
          },
          {
            id: "1.2.5-01016",
            code: "1.2.5.",
            docId: "01016",
            title: "Conclusion (recommendation) of authorized body following preliminary scientific advice",
          },
          {
            id: "1.2.6",
            code: "1.2.6",
            title: "Recommendation of Expert Committee on Medicinal Products under EEC following preliminary scientific advice",
            isFolder: true,
            children: [
              {
                id: "1.2.6-01011",
                code: "1.2.6.",
                docId: "01011",
                title: "Conclusion of Expert Committee on Medicinal Products under EEC following preliminary scientific advice",
              },
              {
                id: "1.2.6-01012",
                code: "1.2.6.",
                docId: "01012",
                title: "Recommendation of Expert Committee on Medicinal Products under EEC following preliminary scientific advice",
              },
            ],
          },
        ],
      },
      {
        id: "1.3",
        code: "1.3",
        title: "Summary of Product Characteristics (SmPC), package leaflet, package mock-ups",
        isFolder: true,
        children: [
          {
            id: "1.3.1",
            code: "1.3.1",
            title: "Drafts of SmPC and package leaflet compiled in accordance with EAEU requirements in Russian",
            isFolder: true,
            children: [
              {
                id: "1.3.1-02001",
                code: "1.3.1.",
                docId: "02001",
                title: "Draft summary of product characteristics (SmPC) in Russian and Kazakh",
              },
              {
                id: "1.3.1-02002",
                code: "1.3.1.",
                docId: "02002",
                title: "Draft package leaflet (patient information leaflet) in Russian and Kazakh",
              },
            ],
          },
          {
            id: "1.3.2",
            code: "1.3.2",
            title: "Mock-ups of primary, secondary, and intermediate packaging",
            isFolder: true,
            children: [
              { id: "1.3.2-02003", code: "1.3.2.", docId: "02003", title: "Draft medicinal product labeling" },
              { id: "1.3.2-02004", code: "1.3.2.", docId: "02004", title: "Mock-up of secondary (consumer) packaging of medicinal product" },
              { id: "1.3.2-02005", code: "1.3.2.", docId: "02005", title: "Mock-up of primary (inner) packaging of medicinal product" },
              { id: "1.3.2-02006", code: "1.3.2.", docId: "02006", title: "Mock-up of intermediate packaging of medicinal product" },
              { id: "1.3.2-02007", code: "1.3.2.", docId: "02007", title: "Mock-up of medicinal product label" },
              { id: "1.3.2-02008", code: "1.3.2.", docId: "02008", title: "Mock-up of medicinal product sticker" },
            ],
          },
          {
            id: "1.3.3-02009",
            code: "1.3.3.",
            docId: "02009",
            title: "Results of user testing of package leaflet mock-up (Annex 12 EAEU Council Decision No. 88)",
          },
          {
            id: "1.3.4",
            code: "1.3.4",
            title: "Copies of approved SmPC and package leaflet from manufacturing country",
            isFolder: true,
            children: [
              {
                id: "1.3.4-02010",
                code: "1.3.4.",
                docId: "02010",
                title: "Summary of product characteristics approved by authorized body of manufacturing or MAH country",
              },
              {
                id: "1.3.4-02011",
                code: "1.3.4.",
                docId: "02011",
                title: "Package leaflet of medicinal product approved by authorized body of manufacturing country",
              },
            ],
          },
        ],
      },
      {
        id: "1.4",
        code: "1.4",
        title: "Information on regulatory status of medicinal product in other countries",
        isFolder: true,
        children: [
          {
            id: "1.4.1-01013",
            code: "1.4.1.",
            docId: "01013",
            title: "List of countries where medicinal product has been submitted, registered, refused, or suspended",
          },
        ],
      },
      {
        id: "1.5",
        code: "1.5",
        title: "Quality Documents",
        isFolder: true,
        children: [
          {
            id: "1.5.1",
            code: "1.5.1",
            title: "Certificates of suitability to EAEU or European Pharmacopoeia monographs regarding TSE",
            isFolder: true,
            children: [
              { id: "1.5.1-03001", code: "1.5.1.", docId: "03001", title: "Certificate of suitability to EAEU Pharmacopoeia monograph" },
              { id: "1.5.1-03002", code: "1.5.1.", docId: "03002", title: "Certificate of suitability to European Pharmacopoeia monograph regarding TSE" },
              { id: "1.5.1-03003", code: "1.5.1.", docId: "03003", title: "Document issued by authorized veterinary supervision bodies of country of origin of raw materials" },
            ],
          },
          {
            id: "1.5.2-03004",
            code: "1.5.2.",
            docId: "03004",
            title: "Letter from Active Substance Master File (ASMF) holder undertaking to report all changes",
          },
          {
            id: "1.5.3-03005",
            code: "1.5.3.",
            docId: "03005",
            title: "Letter confirming ASMF holder's consent to submit restricted part of ASMF dossier upon request",
          },
          {
            id: "1.5.4-03006",
            code: "1.5.4.",
            docId: "03006",
            title: "Copy of certificate of suitability of active substance to European Pharmacopoeia requirements",
          },
          {
            id: "1.5.5-03007",
            code: "1.5.5.",
            docId: "03007",
            title: "Copy of plasma master file certificate issued by authorized body of manufacturing country",
          },
          {
            id: "1.5.6-03008",
            code: "1.5.6.",
            docId: "03008",
            title: "Copy of vaccine antigen master file certificate issued by authorized body of manufacturing country",
          },
          {
            id: "1.5.7-13028",
            code: "1.5.7.",
            docId: "13028",
            title: "Draft quality standard document prepared in accordance with EAEU Guidelines (EEC Decision No. 151)",
          },
        ],
      },
      {
        id: "1.6",
        code: "1.6",
        title: "Manufacturing Documents",
        isFolder: true,
        children: [
          {
            id: "1.6.1",
            code: "1.6.1",
            title: "GMP compliance documents",
            isFolder: true,
            children: [
              { id: "1.6.1-04001", code: "1.6.1.", docId: "04001", title: "Document confirming compliance of manufacturer with EAEU GMP rules" },
              { id: "1.6.1-04002", code: "1.6.1.", docId: "04002", title: "Document confirming manufacturer compliance with GMP issued by site country authority" },
            ],
          },
          {
            id: "1.6.2",
            code: "1.6.2",
            title: "Manufacturing license / authorization copies",
            isFolder: true,
            children: [
              { id: "1.6.2-04003", code: "1.6.2.", docId: "04003", title: "Manufacturing authorization for medicinal products issued by site country authority" },
              { id: "1.6.2-04004", code: "1.6.2.", docId: "04004", title: "Manufacturing license for medicinal products issued by site country authority" },
            ],
          },
          {
            id: "1.6.3",
            code: "1.6.3",
            title: "Manufacturing site inspection reports and CAPA",
            isFolder: true,
            children: [
              { id: "1.6.3-04005", code: "1.6.3.", docId: "04005", title: "Inspection report of manufacturing site for compliance with GMP rules" },
              { id: "1.6.3-04006", code: "1.6.3.", docId: "04006", title: "Corrective and Preventive Action (CAPA) plan following GMP inspection" },
              { id: "1.6.3-04007", code: "1.6.3.", docId: "04007", title: "Corrective and Preventive Action (CAPA) report following GMP inspection" },
            ],
          },
          { id: "1.6.6-04010", code: "1.6.6.", docId: "04010", title: "Information on regulatory measures taken by authorized body based on inspections" },
          { id: "1.6.7-04011", code: "1.6.7.", docId: "04011", title: "Letter from Qualified Person (QP) regarding compliance of manufacturing conditions with GMP" },
          {
            id: "1.6.8",
            code: "1.6.8",
            title: "Product quality complaints information",
            isFolder: true,
            children: [
              { id: "1.6.8-04012", code: "1.6.8.", docId: "04012", title: "Information on product quality complaints" },
              { id: "1.6.8-04013", code: "1.6.8.", docId: "04013", title: "Confirmation of the absence of product quality complaints" },
            ],
          },
          { id: "1.6.9-04014", code: "1.6.9.", docId: "04014", title: "Consent to conduct pharmaceutical inspection for compliance with international treaties and EAEU law" },
          { id: "1.6.11-04016", code: "1.6.11.", docId: "04016", title: "Manufacturing process flow chart indicating all sites involved in drug substance and drug product manufacturing" },
        ],
      },
      {
        id: "1.7",
        code: "1.7",
        title: "Information on Experts",
        isFolder: true,
        children: [
          { id: "1.7.1-05001", code: "1.7.1.", docId: "05001", title: "Information on expert who prepared Quality Overall Summary (QOS)" },
          { id: "1.7.2-05002", code: "1.7.2.", docId: "05002", title: "Information on expert who prepared Non-Clinical Overview/Summaries" },
          { id: "1.7.3-05003", code: "1.7.3.", docId: "05003", title: "Information on expert who prepared Clinical Overview/Summaries" },
        ],
      },
      {
        id: "1.8",
        code: "1.8",
        title: "Specific Requirements for Different Types of Applications",
        isFolder: true,
        children: [
          { id: "1.8.1-01015", code: "1.8.1.", docId: "01015", title: "Marketing authorization holder's letter containing details on additional trade name" },
          {
            id: "1.8.2",
            code: "1.8.2",
            title: "Clinical trial documents",
            isFolder: true,
            children: [
              { id: "1.8.2.1-04017", code: "1.8.2.1.", docId: "04017", title: "Authorization of authorized body for conducting clinical trial in EAEU member states" },
              { id: "1.8.2.2-04018", code: "1.8.2.2.", docId: "04018", title: "List of inspections conducted for compliance with EAEU Good Clinical Practice (GCP) rules" },
              { id: "1.8.2.5-01017", code: "1.8.2.5.", docId: "01017", title: "Overview for registration applications with bibliographical sources and data" },
              { id: "1.8.2.6-01018", code: "1.8.2.6.", docId: "01018", title: "Overview for registration applications of generic, hybrid, or biosimilar medicinal products" },
              { id: "1.8.2.7-01019", code: "1.8.2.7.", docId: "01019", title: "Overview for registration applications when patents exist in member state regarding registered product" },
              { id: "1.8.2.8-01020", code: "1.8.2.8.", docId: "01020", title: "Overview for registration applications in exceptional circumstances" },
              { id: "1.8.2.9-01021", code: "1.8.2.9.", docId: "01021", title: "Overview for registration applications with post-authorization measures (conditional registration)" },
            ],
          },
          { id: "1.8.3-04025", code: "1.8.3.", docId: "04025", title: "Table listing clinical trials" },
        ],
      },
      {
        id: "1.9",
        code: "1.9",
        title: "Applicant's documents on environmental risk assessment",
        isFolder: true,
        children: [
          { id: "1.9.1-06001", code: "1.9.1.", docId: "06001", title: "Applicant's document on environmental risk assessment" },
          { id: "1.9.1-06002", code: "1.9.1.", docId: "06002", title: "Applicant's letter stating whether medicinal products contain or are derived from GMOs" },
        ],
      },
      {
        id: "1.10",
        code: "1.10",
        title: "Information Concerning Pharmacovigilance in EAEU Member State",
        isFolder: true,
        children: [
          {
            id: "1.10.1",
            code: "1.10.1",
            title: "Pharmacovigilance system master file (PSMF) or summary",
            isFolder: true,
            children: [
              { id: "1.10.1-07001", code: "1.10.1.", docId: "07001", title: "PSMF in accordance with EAEU GVP rules (EEC Decision No. 87)" },
              { id: "1.10.1-07002", code: "1.10.1.", docId: "07002", title: "Summary of applicant / MAH pharmacovigilance system" },
            ],
          },
          { id: "1.10.2-07003", code: "1.10.2.", docId: "07003", title: "Written confirmation of QPPV residing/operating in EAEU member state" },
          { id: "1.10.3-07004", code: "1.10.3.", docId: "07004", title: "Risk Management Plan (RMP) in accordance with EAEU GVP rules" },
          { id: "1.10.4-07005", code: "1.10.4.", docId: "07005", title: "Documents confirming interactions ensuring multi-entity fulfillment of MAH obligations" },
        ],
      },
      { id: "1.11-08001", code: "1.11.", docId: "08001", title: "Copies of documents confirming trademark registration" },
    ],
  },
  {
    id: "m2",
    code: "Module 2",
    title: "CTD Summaries",
    isFolder: true,
    children: [
      { id: "2.1-25002", code: "2.1.", docId: "25002", title: "Table of contents of modules 2 – 5" },
      { id: "2.2-09001", code: "2.2.", docId: "09001", title: "Introduction to the Common Technical Document (CTD)" },
      {
        id: "2.3",
        code: "2.3.",
        docId: "09002",
        title: "Quality Overall Summary (QOS)",
        isFolder: true,
        children: [
          {
            id: "2.3.S",
            code: "2.3.S.",
            docId: "09003",
            title: "Drug Substance (Active Substance)",
            isFolder: true,
            children: [
              { id: "2.3.S.1-09004", code: "2.3.S.1.", docId: "09004", title: "Summary of general information regarding starting materials and raw materials" },
              { id: "2.3.S.2-09005", code: "2.3.S.2.", docId: "09005", title: "Summary of manufacturing process of active substance" },
              { id: "2.3.S.3-09006", code: "2.3.S.3.", docId: "09006", title: "Summary of characterization of active substance" },
              { id: "2.3.S.4-09007", code: "2.3.S.4.", docId: "09007", title: "Summary of control of active substance" },
              { id: "2.3.S.5-09008", code: "2.3.S.5.", docId: "09008", title: "Summary of reference standards or materials" },
              { id: "2.3.S.6-09009", code: "2.3.S.6.", docId: "09009", title: "Summary of container closure system" },
              { id: "2.3.S.7-09010", code: "2.3.S.7.", docId: "09010", title: "Summary of stability" },
            ],
          },
          {
            id: "2.3.P",
            code: "2.3.P.",
            docId: "09011",
            title: "Medicinal Product",
            isFolder: true,
            children: [
              { id: "2.3.P.1-09012", code: "2.3.P.1.", docId: "09012", title: "Summary of description and composition of medicinal product" },
              { id: "2.3.P.2-09013", code: "2.3.P.2.", docId: "09013", title: "Summary of pharmaceutical development" },
              { id: "2.3.P.3-09014", code: "2.3.P.3.", docId: "09014", title: "Summary of manufacturing process of medicinal product" },
              { id: "2.3.P.4-09015", code: "2.3.P.4.", docId: "09015", title: "Summary of control of excipients" },
              { id: "2.3.P.5-09016", code: "2.3.P.5.", docId: "09016", title: "Summary of control of finished product" },
              { id: "2.3.P.6-09017", code: "2.3.P.6.", docId: "09017", title: "Summary of reference standards and materials" },
              { id: "2.3.P.7-09018", code: "2.3.P.7.", docId: "09018", title: "Summary of container closure system" },
              { id: "2.3.P.8-09019", code: "2.3.P.8.", docId: "09019", title: "Summary of stability of medicinal product" },
            ],
          },
          {
            id: "2.3.A",
            code: "2.3.A.",
            docId: "09020",
            title: "Appendices",
            isFolder: true,
            children: [
              { id: "2.3.A.1-09021", code: "2.3.A.1.", docId: "09021", title: "Summary of facilities and equipment" },
              { id: "2.3.A.2-09022", code: "2.3.A.2.", docId: "09022", title: "Summary of safety evaluation for extraneous agents" },
              {
                id: "2.3.A.3",
                code: "2.3.A.3.",
                docId: "09023",
                title: "Summary of novel excipients",
                isFolder: true,
                children: [
                  { id: "2.3.A.3.1-09025", code: "2.3.A.3.1.", docId: "09025", title: "Brief information on excipients (reducing agents, solvents, diluents, carriers)" },
                  { id: "2.3.A.3.2-09026", code: "2.3.A.3.2.", docId: "09026", title: "Brief description and composition of excipient" },
                  { id: "2.3.A.3.3-09027", code: "2.3.A.3.3.", docId: "09027", title: "Brief description of pharmaceutical development of excipient" },
                  { id: "2.3.A.3.4-09028", code: "2.3.A.3.4.", docId: "09028", title: "Brief description of manufacturing process of excipient" },
                  { id: "2.3.A.3.5-09032", code: "2.3.A.3.5.", docId: "09032", title: "Batch formula (production recipe) of excipient" },
                  { id: "2.3.A.3.6-09029", code: "2.3.A.3.6.", docId: "09029", title: "Brief description of quality control of excipient" },
                  { id: "2.3.A.3.7-09033", code: "2.3.A.3.7.", docId: "09033", title: "Microbiological characteristics of excipient" },
                  { id: "2.3.A.3.8-09030", code: "2.3.A.3.8.", docId: "09030", title: "Brief description of container closure system for excipient" },
                  { id: "2.3.A.3.9-09031", code: "2.3.A.3.9.", docId: "09031", title: "Brief description of stability of excipient" },
                  { id: "2.3.A.3.10-09034", code: "2.3.A.3.10.", docId: "09034", title: "Compatibility information of excipient" },
                ],
              },
            ],
          },
          { id: "2.3.R-09024", code: "2.3.R.", docId: "09024", title: "Regional information summary" },
        ],
      },
      { id: "2.4-10001", code: "2.4.", docId: "10001", title: "Non-clinical overview" },
      { id: "2.5-11001", code: "2.5.", docId: "11001", title: "Clinical overview" },
      {
        id: "2.6",
        code: "2.6",
        title: "Non-clinical Written and Tabulated Summaries",
        isFolder: true,
        children: [
          { id: "2.6.1-10008", code: "2.6.1.", docId: "10008", title: "Introduction" },
          { id: "2.6.2-10002", code: "2.6.2.", docId: "10002", title: "Pharmacology written summary" },
          { id: "2.6.3-10003", code: "2.6.3.", docId: "10003", title: "Pharmacology tabulated summary" },
          { id: "2.6.4-10004", code: "2.6.4.", docId: "10004", title: "Pharmacokinetics written summary" },
          { id: "2.6.5-10005", code: "2.6.5.", docId: "10005", title: "Pharmacokinetics tabulated summary" },
          { id: "2.6.6-10006", code: "2.6.6.", docId: "10006", title: "Toxicology written summary" },
          { id: "2.6.7-10007", code: "2.6.7.", docId: "10007", title: "Toxicology tabulated summary" },
        ],
      },
      {
        id: "2.7",
        code: "2.7",
        title: "Clinical Summary",
        isFolder: true,
        children: [
          { id: "2.7.1-11002", code: "2.7.1.", docId: "11002", title: "Summary of biopharmaceutics and associated analytical methods" },
          { id: "2.7.2-11003", code: "2.7.2.", docId: "11003", title: "Summary of clinical pharmacology studies" },
          { id: "2.7.3-11004", code: "2.7.3.", docId: "11004", title: "Summary of clinical efficacy" },
          { id: "2.7.4-11005", code: "2.7.4.", docId: "11005", title: "Summary of clinical safety" },
          { id: "2.7.5-11006", code: "2.7.5.", docId: "11006", title: "References / literature copies used" },
          { id: "2.7.6-11007", code: "2.7.6.", docId: "11007", title: "Synopses of individual studies" },
        ],
      },
    ],
  },
  {
    id: "m3",
    code: "Module 3",
    title: "Quality (Chemical, Pharmaceutical and Biological Information)",
    isFolder: true,
    children: [
      { id: "3.1-25003", code: "3.1.", docId: "25003", title: "Table of contents of module 3" },
      {
        id: "3.2",
        code: "3.2",
        title: "Body of Data",
        isFolder: true,
        children: [
          {
            id: "3.2.S",
            code: "3.2.S",
            title: "Active Substance (AS)",
            isFolder: true,
            children: [
              {
                id: "3.2.S.1",
                code: "3.2.S.1",
                title: "General Information",
                isFolder: true,
                children: [
                  { id: "3.2.S.1.1-12001", code: "3.2.S.1.1.", docId: "12001", title: "Nomenclature of active substance" },
                  { id: "3.2.S.1.2-12002", code: "3.2.S.1.2.", docId: "12002", title: "Structure of active substance" },
                  { id: "3.2.S.1.3-12003", code: "3.2.S.1.3.", docId: "12003", title: "General properties of active substance" },
                ],
              },
              {
                id: "3.2.S.2",
                code: "3.2.S.2",
                title: "Manufacture",
                isFolder: true,
                children: [
                  { id: "3.2.S.2.1-12004", code: "3.2.S.2.1.", docId: "12004", title: "Manufacturer" },
                  { id: "3.2.S.2.2-12005", code: "3.2.S.2.2.", docId: "12005", title: "Description of manufacturing process and process controls" },
                  { id: "3.2.S.2.3-12006", code: "3.2.S.2.3.", docId: "12006", title: "Control of materials" },
                  { id: "3.2.S.2.4-12007", code: "3.2.S.2.4.", docId: "12007", title: "Controls of critical steps and intermediates" },
                  { id: "3.2.S.2.5-12008", code: "3.2.S.2.5.", docId: "12008", title: "Process validation and/or evaluation of active substance" },
                  { id: "3.2.S.2.6-12010", code: "3.2.S.2.6.", docId: "12010", title: "Manufacturing process development" },
                ],
              },
              {
                id: "3.2.S.3",
                code: "3.2.S.3",
                title: "Characterization",
                isFolder: true,
                children: [
                  { id: "3.2.S.3.1-12011", code: "3.2.S.3.1.", docId: "12011", title: "Elucidation of structure and other characteristics" },
                  { id: "3.2.S.3.2-12012", code: "3.2.S.3.2.", docId: "12012", title: "Impurities" },
                ],
              },
              {
                id: "3.2.S.4",
                code: "3.2.S.4",
                title: "Control of Active Substance",
                isFolder: true,
                children: [
                  { id: "3.2.S.4.1-12013", code: "3.2.S.4.1.", docId: "12013", title: "Specification" },
                  { id: "3.2.S.4.2-12014", code: "3.2.S.4.2.", docId: "12014", title: "Analytical procedures" },
                  { id: "3.2.S.4.3-12015", code: "3.2.S.4.3.", docId: "12015", title: "Validation of analytical procedures" },
                  { id: "3.2.S.4.4-12016", code: "3.2.S.4.4.", docId: "12016", title: "Batch analyses" },
                  { id: "3.2.S.4.5-12017", code: "3.2.S.4.5.", docId: "12017", title: "Justification of specification" },
                ],
              },
              { id: "3.2.S.5-12018", code: "3.2.S.5.", docId: "12018", title: "Reference standards or materials" },
              { id: "3.2.S.6-12019", code: "3.2.S.6.", docId: "12019", title: "Container closure system" },
              {
                id: "3.2.S.7",
                code: "3.2.S.7",
                title: "Stability",
                isFolder: true,
                children: [
                  { id: "3.2.S.7.1-12020", code: "3.2.S.7.1.", docId: "12020", title: "Stability summary and conclusions" },
                  { id: "3.2.S.7.2-12022", code: "3.2.S.7.2.", docId: "12022", title: "Post-approval stability protocol and stability commitment" },
                  { id: "3.2.S.7.3-12024", code: "3.2.S.7.3.", docId: "12024", title: "Stability data" },
                ],
              },
            ],
          },
          {
            id: "3.2.P",
            code: "3.2.P",
            title: "Medicinal Product",
            isFolder: true,
            children: [
              { id: "3.2.P.1-13001", code: "3.2.P.1.", docId: "13001", title: "Description and composition of medicinal product" },
              {
                id: "3.2.P.2",
                code: "3.2.P.2",
                title: "Pharmaceutical Development",
                isFolder: true,
                children: [
                  {
                    id: "3.2.P.2.1",
                    code: "3.2.P.2.1",
                    title: "Components of medicinal product",
                    isFolder: true,
                    children: [
                      { id: "3.2.P.2.1.1-13004", code: "3.2.P.2.1.1.", docId: "13004", title: "Active substance" },
                      { id: "3.2.P.2.1.2-13005", code: "3.2.P.2.1.2.", docId: "13005", title: "Excipients" },
                    ],
                  },
                  {
                    id: "3.2.P.2.2",
                    code: "3.2.P.2.2",
                    title: "Medicinal Product",
                    isFolder: true,
                    children: [
                      { id: "3.2.P.2.2.1-13007", code: "3.2.P.2.2.1.", docId: "13007", title: "Development of dosage form" },
                      { id: "3.2.P.2.2.2-13008", code: "3.2.P.2.2.2.", docId: "13008", title: "Overages" },
                      { id: "3.2.P.2.2.3-13009", code: "3.2.P.2.2.3.", docId: "13009", title: "Physicochemical and biological properties" },
                    ],
                  },
                  { id: "3.2.P.2.3-13010", code: "3.2.P.2.3.", docId: "13010", title: "Manufacturing process development" },
                  { id: "3.2.P.2.4-13011", code: "3.2.P.2.4.", docId: "13011", title: "Container closure system" },
                  { id: "3.2.P.2.5-13012", code: "3.2.P.2.5.", docId: "13012", title: "Microbiological attributes" },
                  { id: "3.2.P.2.6-13013", code: "3.2.P.2.6.", docId: "13013", title: "Compatibility" },
                ],
              },
              {
                id: "3.2.P.3",
                code: "3.2.P.3",
                title: "Manufacture of Medicinal Product",
                isFolder: true,
                children: [
                  { id: "3.2.P.3.1-13014", code: "3.2.P.3.1.", docId: "13014", title: "Manufacturer(s)" },
                  { id: "3.2.P.3.2-13015", code: "3.2.P.3.2.", docId: "13015", title: "Batch formula (production recipe)" },
                  { id: "3.2.P.3.3-13016", code: "3.2.P.3.3.", docId: "13016", title: "Description of manufacturing process and process controls" },
                  { id: "3.2.P.3.4-13017", code: "3.2.P.3.4.", docId: "13017", title: "Controls of critical steps and intermediates" },
                  { id: "3.2.P.3.5-13018", code: "3.2.P.3.5.", docId: "13018", title: "Process validation and/or evaluation" },
                ],
              },
              {
                id: "3.2.P.4",
                code: "3.2.P.4",
                title: "Control of Excipients",
                isFolder: true,
                children: [
                  { id: "3.2.P.4.1-13020", code: "3.2.P.4.1.", docId: "13020", title: "Specifications" },
                  { id: "3.2.P.4.2-13021", code: "3.2.P.4.2.", docId: "13021", title: "Analytical procedures" },
                  { id: "3.2.P.4.3-13022", code: "3.2.P.4.3.", docId: "13022", title: "Validation of analytical procedures" },
                  { id: "3.2.P.4.4-13023", code: "3.2.P.4.4.", docId: "13023", title: "Justification of specifications" },
                  { id: "3.2.P.4.5-13024", code: "3.2.P.4.5.", docId: "13024", title: "Excipients of human or animal origin" },
                  { id: "3.2.P.4.6-13025", code: "3.2.P.4.6.", docId: "13025", title: "Novel excipients" },
                ],
              },
              {
                id: "3.2.P.5",
                code: "3.2.P.5",
                title: "Control of Finished Product",
                isFolder: true,
                children: [
                  { id: "3.2.P.5.1-13026", code: "3.2.P.5.1.", docId: "13026", title: "Specifications" },
                  { id: "3.2.P.5.2-13027", code: "3.2.P.5.2.", docId: "13027", title: "Analytical procedures" },
                  { id: "3.2.P.5.3-13029", code: "3.2.P.5.3.", docId: "13029", title: "Validation of analytical procedures" },
                  { id: "3.2.P.5.4-13030", code: "3.2.P.5.4.", docId: "13030", title: "Batch analyses" },
                  { id: "3.2.P.5.5-13031", code: "3.2.P.5.5.", docId: "13031", title: "Characterization of impurities" },
                  { id: "3.2.P.5.6-13032", code: "3.2.P.5.6.", docId: "13032", title: "Justification of specifications" },
                ],
              },
              { id: "3.2.P.6-13033", code: "3.2.P.6.", docId: "13033", title: "Reference standards or materials" },
              { id: "3.2.P.7-13034", code: "3.2.P.7.", docId: "13034", title: "Container closure system" },
              {
                id: "3.2.P.8",
                code: "3.2.P.8",
                title: "Stability of Medicinal Product",
                isFolder: true,
                children: [
                  { id: "3.2.P.8.1-13035", code: "3.2.P.8.1.", docId: "13035", title: "Stability summary and conclusions" },
                  { id: "3.2.P.8.2-13037", code: "3.2.P.8.2.", docId: "13037", title: "Post-approval stability protocol and stability commitment" },
                  { id: "3.2.P.8.3-13038", code: "3.2.P.8.3.", docId: "13038", title: "Stability data" },
                ],
              },
            ],
          },
          {
            id: "3.2.A",
            code: "3.2.A",
            title: "Appendices",
            isFolder: true,
            children: [
              { id: "3.2.A.1-13040", code: "3.2.A.1.", docId: "13040", title: "Facilities and equipment" },
              { id: "3.2.A.2-13041", code: "3.2.A.2.", docId: "13041", title: "Safety evaluation of medicinal products regarding extraneous agents" },
              {
                id: "3.2.A.3",
                code: "3.2.A.3",
                title: "Novel Excipients",
                isFolder: true,
                children: [
                  { id: "3.2.A.3.1-13044", code: "3.2.A.3.1.", docId: "13044", title: "Information on excipients (reducing agents, solvents, diluents, carriers)" },
                  { id: "3.2.A.3.2-13045", code: "3.2.A.3.2.", docId: "13045", title: "Description and composition of excipient" },
                  { id: "3.2.A.3.3-13046", code: "3.2.A.3.3.", docId: "13046", title: "Pharmaceutical development of excipient" },
                  { id: "3.2.A.3.4-13048", code: "3.2.A.3.4.", docId: "13048", title: "Manufacturing process of excipient" },
                  { id: "3.2.A.3.5-13067", code: "3.2.A.3.5.", docId: "13067", title: "Batch formula of excipient" },
                  { id: "3.2.A.3.6-13058", code: "3.2.A.3.6.", docId: "13058", title: "Quality control of excipient" },
                  { id: "3.2.A.3.7-13052", code: "3.2.A.3.7.", docId: "13052", title: "Microbiological characteristics of excipient" },
                  { id: "3.2.A.3.8-13065", code: "3.2.A.3.8.", docId: "13065", title: "Container closure system for excipient" },
                  { id: "3.2.A.3.9-13068", code: "3.2.A.3.9.", docId: "13068", title: "Stability of excipient" },
                  { id: "3.2.A.3.10-13066", code: "3.2.A.3.10.", docId: "13066", title: "Compatibility information of excipient" },
                ],
              },
            ],
          },
          { id: "3.2.R.2-04026", code: "3.2.R.2.", docId: "04026", title: "Production process validation plan" },
        ],
      },
      { id: "3.3-25004", code: "3.3.", docId: "25004", title: "Literature references" },
    ],
  },
  {
    id: "m4",
    code: "Module 4",
    title: "Non-Clinical Study Reports",
    isFolder: true,
    children: [
      { id: "4.1-25005", code: "4.1.", docId: "25005", title: "Table of contents of module 4" },
      {
        id: "4.2",
        code: "4.2.",
        title: "Study Reports",
        isFolder: true,
        children: [
          {
            id: "4.2.1",
            code: "4.2.1.",
            title: "Pharmacology",
            isFolder: true,
            children: [
              { id: "4.2.1.1-14001", code: "4.2.1.1.", docId: "14001", title: "Primary pharmacodynamics" },
              { id: "4.2.1.2-14002", code: "4.2.1.2.", docId: "14002", title: "Secondary pharmacodynamics" },
              { id: "4.2.1.3-14003", code: "4.2.1.3.", docId: "14003", title: "Safety pharmacology" },
              { id: "4.2.1.4-14004", code: "4.2.1.4.", docId: "14004", title: "Pharmacodynamic drug interactions" },
            ],
          },
          {
            id: "4.2.2",
            code: "4.2.2.",
            title: "Pharmacokinetics",
            isFolder: true,
            children: [
              { id: "4.2.2.1-15001", code: "4.2.2.1.", docId: "15001", title: "Analytical procedures and validation reports" },
              { id: "4.2.2.2-15003", code: "4.2.2.2.", docId: "15003", title: "Absorption" },
              { id: "4.2.2.3-15004", code: "4.2.2.3.", docId: "15004", title: "Distribution" },
              { id: "4.2.2.4-15005", code: "4.2.2.4.", docId: "15005", title: "Metabolism" },
              { id: "4.2.2.5-15006", code: "4.2.2.5.", docId: "15006", title: "Excretion" },
              { id: "4.2.2.6-15007", code: "4.2.2.6.", docId: "15007", title: "Pharmacokinetic drug interactions" },
              { id: "4.2.2.7-15008", code: "4.2.2.7.", docId: "15008", title: "Other pharmacokinetic studies" },
            ],
          },
          {
            id: "4.2.3",
            code: "4.2.3.",
            title: "Toxicology",
            isFolder: true,
            children: [
              { id: "4.2.3.1-16001", code: "4.2.3.1.", docId: "16001", title: "Single-dose toxicity" },
              { id: "4.2.3.2-16002", code: "4.2.3.2.", docId: "16002", title: "Repeat-dose toxicity" },
              {
                id: "4.2.3.3",
                code: "4.2.3.3",
                title: "Genotoxicity",
                isFolder: true,
                children: [
                  { id: "4.2.3.3.1-16003", code: "4.2.3.3.1.", docId: "16003", title: "In vitro genotoxicity studies" },
                  { id: "4.2.3.3.2-16004", code: "4.2.3.3.2.", docId: "16004", title: "In vivo genotoxicity studies" },
                ],
              },
              {
                id: "4.2.3.4",
                code: "4.2.3.4",
                title: "Carcinogenicity",
                isFolder: true,
                children: [
                  { id: "4.2.3.4.1-16017", code: "4.2.3.4.1.", docId: "16017", title: "Long-term studies" },
                  { id: "4.2.3.4.2-16018", code: "4.2.3.4.2.", docId: "16018", title: "Short- or medium-term studies" },
                  { id: "4.2.3.4.3-16019", code: "4.2.3.4.3.", docId: "16019", title: "Other carcinogenicity studies" },
                ],
              },
              {
                id: "4.2.3.5",
                code: "4.2.3.5",
                title: "Reproductive and developmental toxicity",
                isFolder: true,
                children: [
                  { id: "4.2.3.5.1-16005", code: "4.2.3.5.1.", docId: "16005", title: "Fertility and early embryonic development" },
                  { id: "4.2.3.5.2-16006", code: "4.2.3.5.2.", docId: "16006", title: "Embryo-fetal development" },
                  { id: "4.2.3.5.3-16007", code: "4.2.3.5.3.", docId: "16007", title: "Prenatal and postnatal development" },
                  { id: "4.2.3.5.4-16008", code: "4.2.3.5.4.", docId: "16008", title: "Studies in which offspring are juvenile and/or further evaluated" },
                ],
              },
              { id: "4.2.3.6-16009", code: "4.2.3.6.", docId: "16009", title: "Local tolerance" },
              {
                id: "4.2.3.7",
                code: "4.2.3.7",
                title: "Other toxicity studies",
                isFolder: true,
                children: [
                  { id: "4.2.3.7.1-16011", code: "4.2.3.7.1.", docId: "16011", title: "Antigenicity" },
                  { id: "4.2.3.7.2-16012", code: "4.2.3.7.2.", docId: "16012", title: "Immunotoxicity" },
                  { id: "4.2.3.7.3-16013", code: "4.2.3.7.3.", docId: "16013", title: "Mechanistic studies" },
                  { id: "4.2.3.7.4-16014", code: "4.2.3.7.4.", docId: "16014", title: "Dependence" },
                  { id: "4.2.3.7.5-16015", code: "4.2.3.7.5.", docId: "16015", title: "Metabolites" },
                  { id: "4.2.3.7.6-16016", code: "4.2.3.7.6.", docId: "16016", title: "Impurities" },
                  { id: "4.2.3.7.7-16010", code: "4.2.3.7.7.", docId: "16010", title: "Other toxicological studies" },
                ],
              },
            ],
          },
        ],
      },
      { id: "4.3-25006", code: "4.3.", docId: "25006", title: "Literature references" },
    ],
  },
  {
    id: "m5",
    code: "Module 5",
    title: "Clinical Study Reports",
    isFolder: true,
    children: [
      { id: "5.1-25007", code: "5.1.", docId: "25007", title: "Table of contents of module 5" },
      { id: "5.2-17001", code: "5.2.", docId: "17001", title: "Tabular listing of all clinical studies" },
      {
        id: "5.3",
        code: "5.3",
        title: "Clinical Study Reports",
        isFolder: true,
        children: [
          {
            id: "5.3.1",
            code: "5.3.1",
            title: "Reports of Biopharmaceutic Studies",
            isFolder: true,
            children: [
              { id: "5.3.1.1-17002", code: "5.3.1.1.", docId: "17002", title: "Bioavailability (BA) study reports" },
              { id: "5.3.1.2-17003", code: "5.3.1.2.", docId: "17003", title: "Comparative BA and bioequivalence (BE) study reports" },
              { id: "5.3.1.3-17005", code: "5.3.1.3.", docId: "17005", title: "In vitro – in vivo correlation study reports" },
              { id: "5.3.1.4-17006", code: "5.3.1.4.", docId: "17006", title: "Reports of bioanalytical and analytical methods for human studies" },
            ],
          },
          {
            id: "5.3.2",
            code: "5.3.2",
            title: "Reports of Studies Pertinent to Pharmacokinetics Using Human Biomaterials",
            isFolder: true,
            children: [
              { id: "5.3.2.1-18001", code: "5.3.2.1.", docId: "18001", title: "Plasma protein binding study reports" },
              { id: "5.3.2.2-18002", code: "5.3.2.2.", docId: "18002", title: "Hepatic metabolism and drug interaction study reports" },
              { id: "5.3.2.3-18003", code: "5.3.2.3.", docId: "18003", title: "Studies using other human biomaterials" },
            ],
          },
          {
            id: "5.3.3",
            code: "5.3.3",
            title: "Reports of Human Pharmacokinetic (PK) Studies",
            isFolder: true,
            children: [
              { id: "5.3.3.1-19001", code: "5.3.3.1.", docId: "19001", title: "Healthy volunteer PK and initial tolerability study reports" },
              { id: "5.3.3.2-19002", code: "5.3.3.2.", docId: "19002", title: "Patient PK and initial tolerability study reports" },
              { id: "5.3.3.3-19003", code: "5.3.3.3.", docId: "19003", title: "Intrinsic factor PK study reports" },
              { id: "5.3.3.4-19004", code: "5.3.3.4.", docId: "19004", title: "Extrinsic factor PK study reports" },
              { id: "5.3.3.5-19005", code: "5.3.3.5.", docId: "19005", title: "Population pharmacokinetic study reports" },
            ],
          },
          {
            id: "5.3.4",
            code: "5.3.4",
            title: "Reports of Human Pharmacodynamic (PD) Studies",
            isFolder: true,
            children: [
              { id: "5.3.4.1-20001", code: "5.3.4.1.", docId: "20001", title: "Healthy volunteer PD and PK/PD study reports" },
              { id: "5.3.4.2-20005", code: "5.3.4.2.", docId: "20005", title: "Patient PD and PK/PD study reports" },
            ],
          },
          {
            id: "5.3.5",
            code: "5.3.5",
            title: "Reports of Efficacy and Safety Studies",
            isFolder: true,
            children: [
              { id: "5.3.5.1-21001", code: "5.3.5.1.", docId: "21001", title: "Reports of controlled clinical studies pertinent to requested indication" },
              { id: "5.3.5.2-22001", code: "5.3.5.2.", docId: "22001", title: "Reports of uncontrolled clinical studies" },
              { id: "5.3.5.3-22002", code: "5.3.5.3.", docId: "22002", title: "Reports of analyses of data from more than one study" },
              { id: "5.3.5.4-22003", code: "5.3.5.4.", docId: "22003", title: "Other clinical study reports" },
            ],
          },
          { id: "5.3.6-23001", code: "5.3.6.", docId: "23001", title: "Reports of post-marketing experience" },
          {
            id: "5.3.7",
            code: "5.3.7",
            title: "Case Report Forms and Individual Patient Listings",
            isFolder: true,
            children: [
              { id: "5.3.7-24001", code: "5.3.7.", docId: "24001", title: "Case report forms" },
              { id: "5.3.7-24002", code: "5.3.7.", docId: "24002", title: "Individual patient data listings" },
            ],
          },
        ],
      },
      { id: "5.4-25008", code: "5.4.", docId: "25008", title: "Literature references" },
    ],
  },
];
